# Uncomment this line to define a global platform for your project
platform :ios, '6.0'

pod "SYPickUpMotion", :path => "../"

# Uncomment the following lines to add testing dependencies
# target "DemoTests" do
#   pod 'Expecta'
# end

